
include_recipe 'vm::base'
include_recipe 'vm::bash'
include_recipe 'vm::git'
include_recipe 'vm::ansible'
include_recipe 'vm::chefdk'
include_recipe 'vm::virtualbox'
include_recipe 'vm::vagrant'
include_recipe 'vm::packer'
include_recipe 'vm::atom'
include_recipe 'vm::docker'
include_recipe 'vm::vscode'